spring:
  application:
    name: vehicle-marketplace
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:aws}
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vehiclemarketplace}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      auto-commit: true
  
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-version: 1
    validate-on-migrate: true

  security:
    # Configurações OAuth2 removidas

server:
  port: 8082
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.vehiclemarketplace: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret}
    expiration-ms: 86400000
    issuer: vehicle-marketplace
  
  aws:
    region: ${AWS_REGION:us-east-1}
    s3:
      bucket-name: ${S3_BUCKET_NAME:vehicle-marketplace-bucket}
    sqs:
      queue-url: ${SQS_QUEUE_URL:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.75,0.9,0.95,0.99
      sla:
        http.server.requests: 100ms,200ms,500ms,1s,5s

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
  show-actuator: true
